### Environment constants 

ARCH ?=
CROSS_COMPILE ?=
export

### general build targets

all:
	$(MAKE) all -e -C libloragw
	$(MAKE) all -e -C downlink

clean:
	$(MAKE) clean -e -C libloragw
	$(MAKE) clean -e -C downlink

### EOF
